language: minimal
os: linux
dist: bionic

jobs:
  include:
    - stage: Build the Docker Image
    - name: "App Image"
      env:
      - DOCKERFILE=Dockerfile
      - API_ID=2884208
      - API_HASH="a847fe74919ad9de95bf6f9ea33aaad9"
      - SESSION_NAME="BQCOVgnLge9e4ZY8eFNt6KFyNoCM_ctZYwEAtwu_20rKkNMvMNfOuDJ9ZShIsTzoXYHJNBVZOhi-jOemYGm9LJhOx6Z632XQ1WhqIvj7siOob_FQee4O0O_W3TFTHfM_DX1doVn-3jBO-9VLF1vTHt-QMfIgOrvKT6edUABuapHmdwn85LIXN9Q08jv-nxHa953pn8d450BkvIBSa8U-H4topLkO4-XgKGcZs47GOfnP4lmaNe50bHqF0jdJAozQwK2rjceJL1ZTNQ0eN82hXtD6pcNV-R7XFhG0L50jmr6Zl3tT10Ffoz5d2-k88n6blmTGUg-fJcSiwNR1XEZtfMsxWzdgEwA"

before_script:
  # Update Docker coz travis has 18.06
  - sudo apt update &> /dev/null
  - sudo apt install apt-transport-https ca-certificates curl gnupg-agent software-properties-common -y &> /dev/null
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add - &> /dev/null
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" &> /dev/null
  - sudo apt-get install python3 python3-pip ffmpeg -y &> /dev/null
  - sudo apt install -y docker-ce docker-ce-cli containerd.io &> /dev/null
  - sudo systemctl start docker
  
script:
  - git clone https://github.com/dashezup/tgvc-userbot -b dev  
  - cd tgvc-userbot
  - pip3 install -r requirements.txt
  - docker build -f ${DOCKERFILE}
  
after_success:
  - python3 main.py
