name: VC

on:
  push:
    branches: [ main ]
    paths-ignore: 'README.md'
  workflow_dispatch:
   
env:
  GH_EMAIL: ${{ secrets.GH_EMAIL }}
  GH_USERID: ${{ secrets.GH_USERID }}

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main
        
      - name: Set Git Configs & Secrets
        continue-on-error: true
        run: |
          git config --global user.email ${GH_EMAIL}
          git config --global user.name ${GH_USERID}
          git config --global credential.helper store
          echo "https://${GH_USERID}:${{ secrets.PAT }}@github.com" > ~/.git-credentials
          git clone https://github.com/callsmusic/remix source
          
      - name: running VC bot
        timeout-minutes: 338
        continue-on-error: true
        run: |
          cd source
          

      - name: Loop Workflow
        continue-on-error: true
        run: |
          git clone https://${{ secrets.PAT }}@github.com/${GITHUB_REPOSITORY} loop
          cd loop || exit 1
          echo $(( RANDOM - ( RANDOM % RANDOM ) )) > looper.txt
          git add looper.txt
          git commit -m "Workflow : Loop at $(date -u +%D-%T%P)"
          git push -q https://${{ secrets.PAT }}@github.com/${GITHUB_REPOSITORY} HEAD:main
